name: media
services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/jellyfin:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/media:/data/media
        ports:
            - 8096:8096
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                      - driver: nvidia
                        count: 1
                        capabilities: [gpu]
                        
    
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/lidarr:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data:/data
        ports:
            - 8686:8686
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/radarr:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data:/data
        ports:
            - 7878:7878
        restart: unless-stopped
    
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/sonarr:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data:/data
        ports:
            - 8989:8989
        restart: unless-stopped
    
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        restart: unless-stopped
        environment:
            - VPN_SERVICE_PROVIDER=protonvpn
            - OPENVPN_USER=Bzhbw8aGxwH259mA+pmp
            - OPENVPN_PASSWORD=otGpYfv7eR62ocW85otgwq6TgWGKw33Z
            - VPN_PORT_FORWARDING=on
            - SERVER_COUNTRIES=Canada
            - SERVER_CITIES=Toronto
            - SERVER_HOSTNAMEs=CA#361,CA#362,CA#363
        ports:
            - 6081:6881
            - 6081:6881/udp
            - 8080:8080
    
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
            - WEBUI_PORT=8080
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/qbittorrent:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/torrents:/data/torrents
        restart: unless-stopped
    
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/prowlarr:/config
        ports:
            - 9696:9696
        restart: unless-stopped
    
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/bazarr:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data:/data
        ports:
            - 6767:6767
        restart: unless-stopped
    
    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=America/Winnipeg
        volumes:
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data/configs/readarr:/config
            - /mnt/c0799dcb-68b6-4380-a2db-8ed98ebcfda3/data:/data
        ports:
            - 8787:8787
        restart: unless-stopped
    
    flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
        - LOG_LEVEL=${LOG_LEVEL:-info}
        - LOG_HTML=${LOG_HTML:-false}
        - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
        - TZ=America/Winnipeg
        ports:
        - "${PORT:-8191}:8191"
        restart: unless-stopped 
    
